In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')

In [2]:
ds=pd.read_csv("data.csv")

In [3]:
ds.head()

,Unnamed: 0,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,TARGET(PRICE_IN_LACS)
0,0,Owner,0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",55.0
1,1,Dealer,0,0,2,BHK,1275.000000,1,1,"Vishweshwara Nagar,Mysore",51.0
2,2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",43.0
3,3,Owner,0,1,2,BHK,929.921143,1,1,"Sector-1 Vaishali,Ghaziabad",62.5
4,4,Dealer,1,0,2,BHK,999.009247,0,1,"New Town,Kolkata",60.5

In [4]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             29451 non-null  int64
 1   POSTED_BY              29451 non-null  object
 2   UNDER_CONSTRUCTION     29451 non-null  int64
 3   RERA                   29451 non-null  int64
 4   BHK_NO.                29451 non-null  int64
 5   BHK_OR_RK              29451 non-null  object
 6   SQUARE_FT              29451 non-null  float64
 7   READY_TO_MOVE          29451 non-null  int64
 8   RESALE                 29451 non-null  int64
 9   ADDRESS                29451 non-null  object
 10  TARGET(PRICE_IN_LACS)  29451 non-null  float64
dtypes: float64(2), int64(6), object(3)
memory usage: 2.5+ MB

In [16]:
ds.rename(columns={"ADDRESS":"CITY"},inplace=True)
ds.rename(columns={"BHK_NO.":"BHK_NO"},inplace=True)
ds.rename(columns={"TARGET(PRICE_IN_LACS)":"Price"},inplace=True)

In [17]:
#ds=ds.drop(columns=["UNDER_CONSTRUCTION","RERA","READY_TO_MOVE","RESALE","Unnamed: 0"]) #this is run so not shwoing there for it is comment

In [18]:
ds #All is good

,POSTED_BY,BHK_NO,BHK_OR_RK,SQUARE_FT,CITY,Price
0,Owner,2,BHK,1300.236407,"Ksfc Layout,Bangalore",55.0
1,Dealer,2,BHK,1275.000000,"Vishweshwara Nagar,Mysore",51.0
2,Owner,2,BHK,933.159722,"Jigani,Bangalore",43.0
3,Owner,2,BHK,929.921143,"Sector-1 Vaishali,Ghaziabad",62.5
4,Dealer,2,BHK,999.009247,"New Town,Kolkata",60.5
...,...,...,...,...,...,...
29446,Owner,3,BHK,2500.000000,"Shamshabad Road,Agra",45.0
29447,Owner,2,BHK,769.230769,"E3-108, Lake View Recidency,,Vapi",16.0
29448,Dealer,2,BHK,1022.641509,"Ajmer Road,Jaipur",27.1
29449,Owner,2,BHK,927.079009,"Sholinganallur,Chennai",67.0
29450,Dealer,2,BHK,896.774194,"Jagatpura,Jaipur",27.8

In [19]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   POSTED_BY  29451 non-null  object
 1   BHK_NO     29451 non-null  int64
 2   BHK_OR_RK  29451 non-null  object
 3   SQUARE_FT  29451 non-null  float64
 4   CITY       29451 non-null  object
 5   Price      29451 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.3+ MB

In [86]:
#Quality check
# city : have large address
#city have nan value

In [39]:
ds["POSTED_BY"].unique()
ds["POSTED_BY"].isna().unique()

array([False])

In [21]:
ds["BHK_NO"].isna().unique() #first check unique then na

array([False])

In [22]:
ds["BHK_OR_RK"].isna().unique()

array([False])

In [23]:
ds["SQUARE_FT"].isna().unique()

array([False])

In [24]:
ds["CITY"].isna().unique()

array([False])

In [25]:
ds["Price"].isna().unique()

array([False])

In [26]:
ds["CITY"]=ds["CITY"].str.split().str.get(1).str.replace(","," ")

In [27]:
ds["CITY"]=ds["CITY"].str.split().str.get(1)

In [28]:
ds["CITY"].unique()

array(['Bangalore', 'Mysore', nan, 'Ghaziabad', 'Kolkata', 'Kochi',
       'Siliguri', 'Noida', 'Raigad', 'Wardha', 'Mumbai', 'Nagpur',
       'Mohali', 'Deoghar', 'Jaipur', 'Lalitpur', 'Maharashtra', 'Kanpur',
       'Gurgaon', 'Vadodara', 'Indore', 'Valsad', 'Surat', 'Amravati',
       'Guwahati', 'Chandigarh', 'Shimla', 'Gwalior', 'Bhopal', 'Vapi',
       'Rajkot', 'Raipur', 'Pune', 'Berhampur', 'Faridabad', 'Chennai',
       'Latur', 'Panchkula', 'Bhubaneswar', 'Sonipat', 'Vijayawada',
       'Jabalpur', 'Visakhapatnam', 'Hosur', 'Vizianagaram', 'Morbi',
       'Hubli', 'Karnal', 'Pondicherry', 'Patna', 'Bilaspur', 'Allahabad',
       'Amritsar', 'Patiala', 'Lucknow', 'Ernakulam', 'Varanasi',
       'Bharuch', 'Bhilai', 'Secunderabad', 'Jalgaon', 'Jamshedpur',
       'Mangalore', 'Aurangabad', 'Neemrana', 'Agra', 'ranchi',
       'Ludhiana', 'Goa', 'Bahadurgarh', 'Palghar', 'Meerut',
       'Coimbatore', 'next', 'Dhule', 'Dehradun', 'Anand', 'Bhiwadi',
       'Jamnagar', 'Kottayam', 'Ratnagiri', 'Tirupati', 'Navsari', 'Kota',
       'Jagdalpur', 'Panipat', 'Alwar', 'Asansol', 'Jhunjhunu',
       'Gandhidham', 'Junagadh', 'Ahmednagar', 'Solapur', 'Jalna',
       'Bhiwani', 'Gandhinagar', 'Vakola', 'Eluru', 'Akola', 'Jind',
       'Ambala', 'Bhavnagar', 'Hajipur', 'Jalandhar', 'Dharuhera',
       'Dharwad', 'Ooty', 'Bhandara', 'Guntur', 'Barabanki', 'Rajpura',
       'Ajmer', 'Avadi', 'Erode', 'Panaji', 'Ongole', 'Muzaffarpur',
       'Kolhapur', 'Aligarh', 'Dalhousie', 'Nellore', 'Dhanbad',
       'Kakinada', 'Udaipur', 'Madurai', 'Jodhpur', 'Near', 'Nainital',
       'Udupi', 'Ranchi', 'Bardhaman', 'Chandrapur', 'Bokaro', 'Durgapur',
       'akshaya', 'Roorkee', 'Amroha', 'Kanchipuram', 'mylapore', 'Harda',
       'Ujjain', 'Belgaum', 'Thoothukudi', 'Durg', 'Cuttack', 'Rewari',
       'Puri', 'Karjat', 'Kadapa', 'Rayagada', 'Godhra', 'Mathura',
       'Jhansi', 'Hathras', 'Chhindwara', 'Jivarajpark', 'phase',
       'Bikaner', 'Haridwar', 'Kollam', 'Rewa', 'Porbandar', 'Nagaur',
       'Rishikesh', 'Rourkela', 'Kurukshetra', 'Margao', 'Hazaribagh',
       'Kurnool', 'Gaya', 'Karad', 'Solan', 'LATMA', 'Jammu', 'Bareilly',
       'Nadiad', 'Arrah', 'Bhimavaram', 'Karwar', 'Dahod', 'Rudrapur',
       'Shirdi', 'Hoshangabad', 'Satna', 'Raisen', 'Hoshiarpur',
       'lekhraj', 'Rohtak', 'Haldwani', 'Gadarwara', 'Kotdwara',
       'Sindhudurg', 'Tirunelveli', 'Palwal', 'Govindpuram', 'Thrissur',
       'Gulbarga', 'Srikakulam', 'Nanded', 'Budha', 'Haldia', 'Thanjavur',
       'Beed', 'Sarfabad', 'Telangana', 'Nadiad-MahemdabadRoad',
       'Moradabad', 'Chak', 'Bharatpur', 'Siwan', 'Washim', 'medavakkam'],
      dtype=object)

In [33]:
ds=ds[~ds["CITY"].isna()]

In [36]:
ds=ds.reset_index(drop=True)

In [37]:
ds

      POSTED_BY  BHK_NO BHK_OR_RK    SQUARE_FT       CITY  Price
0         Owner       2       BHK  1300.236407  Bangalore   55.0
1        Dealer       2       BHK  1275.000000     Mysore   51.0
2         Owner       2       BHK   929.921143  Ghaziabad   62.5
3        Dealer       2       BHK   999.009247    Kolkata   60.5
4         Owner       3       BHK  1250.000000      Kochi   42.0
...         ...     ...       ...          ...        ...    ...
12551   Builder       3       BHK  1652.634861   Gulbarga   53.0
12552    Dealer       3       BHK  1554.968123   Lalitpur  200.0
12553    Dealer       1       BHK   752.049334     Mumbai  100.0
12554     Owner       3       BHK  2500.000000       Agra   45.0
12555    Dealer       2       BHK  1022.641509     Jaipur   27.1

[12556 rows x 6 columns]

In [41]:
ds.to_csv("Cle@ned_data.csv")